--[[ GATE MODEL
    This defines the structure of a GateModel.
    It's the visual representation of a Gate object (Model Instance).
    
    A TGateModel should be a Model with the following children
    - Decorations: Folder
      - Main: BasePart ( Will be changed on the great Visuals update )
      - Others
    - Nodes: Folder
      - List of NodePrefabs
    - Base: BasePart (2x0.3x2)
]]

-- Requires and Services
local Visuals = require(script.Visuals)

-- Prefabs
local PrefabsFolder = script.Prefabs
local NodePrefab: Part = PrefabsFolder.Nodes.Basic

-- Constants
local BASE_SIZE = Vector3.new(2, 0.3, 2)
-- This represents the transformation of moving up and back to prevent clipping down and sticking out
local NODE_DEPTH_OFFSET = CFrame.new(0, (NodePrefab.Size.Y + BASE_SIZE.Y) / 2, NodePrefab.Size.Z / 2)

-- ----------------------------- ---------- TYPE DEFINITIONS ----------- -----------------------------

type TEdge = "front" | "back" | "left" | "right"
type TEdgeBoolset = { front: boolean, back: boolean, left: boolean, right: boolean }

export type TGateModel = Model & {
  Decoration: Folder & { Main: BasePart | Model },
  Nodes: Folder,
  Base: BasePart | Model,
}

export type TVisuals = Visuals.TVisuals

-- ----------------------------- ---------- HELPER FUNCTIONS ---------- ---------------------------

local function GetAsPart(object: BasePart | Model): BasePart
  return if object:IsA("BasePart") then object elseif object.PrimaryPart then object.PrimaryPart else error("Object was not a Model or did not have a PrimaryPart set!")
end

-- This function expects a Prepared Offset from GateVisualService.
-- Long story short: X < [-0.5, 0.5], Y < if Input [-0.15, 0.5] else [-0.5, -0.27].
--                  |X| == 0.5 Or |Y| == 0.5 always.
-- To prevent floating-point errors, I check against 1 / 10^9
-- It can be demonstrated that the biggest error is 2^-53 (or ~ 1 / 10^16)
--   but just in case...
local function EdgeFromOffset(preparedOffset: Vector2): TEdge
  local function AlmostEqual(a: number, b: number): boolean return math.abs(a - b) < 1e-9 end  
  if     AlmostEqual(preparedOffset.Y,-0.5) then return "front"
  elseif AlmostEqual(preparedOffset.Y, 0.5) then return "back"
  elseif AlmostEqual(preparedOffset.X,-0.5) then return "left"
  elseif AlmostEqual(preparedOffset.X, 0.5) then return "right" end
  error("Prepared Offset was not prepared. Make sure it is a Vector2 generated by GateVisualService, or validate if sent from client.")
end

-- WireAttachment is on the back face. Should always point OUT of the gate
local RotationForEdge: { [TEdge]: CFrame } = {
  front = CFrame.Angles(0, 0, 0),
  back  = CFrame.Angles(0, math.rad(180), 0),
  left  = CFrame.Angles(0, math.rad(90), 0),
  right = CFrame.Angles(0, math.rad(270), 0)
}

-- Magic!
-- Scales a part to make room for nodes.
-- The part is assumed to be centered
local function MakeRoomForNodes(part: BasePart, edgesWithNode: TEdgeBoolset): (Vector3, Vector3)
  -- Calculate current distances from part's edges to Base's edges
  local leftDist  = (BASE_SIZE.X - part.Size.X) / 2
  local rightDist = leftDist
  local frontDist = (BASE_SIZE.Z - part.Size.Z) / 2
  local backDist  = frontDist
  
  -- Calculate needed shrink per side (only if current distance < NODE_DEPTH)
  local shrinkLeft  = if edgesWithNode.left  then math.max(NodePrefab.Size.Z - leftDist,  0) else 0
  local shrinkRight = if edgesWithNode.right then math.max(NodePrefab.Size.Z - rightDist, 0) else 0
  local shrinkFront = if edgesWithNode.front then math.max(NodePrefab.Size.Z - frontDist, 0) else 0
  local shrinkBack  = if edgesWithNode.back  then math.max(NodePrefab.Size.Z - backDist,  0) else 0
  
  -- New size is equal to the old size minus total shrink on each axis
  local newSizeX = math.max(part.Size.X - (shrinkLeft + shrinkRight), 0)
  local newSizeZ = math.max(part.Size.Z - (shrinkFront + shrinkBack), 0)
  
  -- Calculate position offset to keep center aligned
  -- Move center away (Oposite axix to direction) from edges that are shrinking to compensate
  local offsetX = (shrinkLeft - shrinkRight) / 2
  local offsetZ = (shrinkFront - shrinkBack) / 2
  
  return Vector3.new(newSizeX, part.Size.Y, newSizeZ), Vector3.new(offsetX, 0, offsetZ)
end

-- ----------------------------- --------- NODE INSTANTIATION --------- ---------------------------

-- Instantiates a node.
local function InstantiateNode(name: string, nameColor: Color3, material: Enum.Material, offset: Vector2, model: TGateModel): TEdge
  local node = NodePrefab:Clone()
  node.Name = name
  node.Material = material
  node.Parent = model.Nodes
  
  do -- Set name and color in billboardGui
    local billboardGui = node:FindFirstChildWhichIsA("BillboardGui")
    if billboardGui then
      local textLabel = billboardGui:FindFirstChildWhichIsA("TextLabel")
      if textLabel then
        textLabel.Text = name
        textLabel.TextColor3 = nameColor
      end
    end
  end
  
  local edge: TEdge = EdgeFromOffset(offset)
  
  -- Linear transformation: EdgePosition × Rotation × Offset
  local transformedOffset = CFrame.new(Vector3.new(offset.X * BASE_SIZE.X, 0, offset.Y * BASE_SIZE.Z))
  node.CFrame = GetAsPart(model.Base).CFrame * transformedOffset * RotationForEdge[edge] * NODE_DEPTH_OFFSET
  return edge
end

local function InstantiateOutputNode(name: string, offset: Vector2, model: TGateModel): TEdge
  return InstantiateNode(name, Color3.new(0.8, 0.1, 0.15), Enum.Material.Neon, offset, model)
end

local function InstantiateInputNode(name: string, offset: Vector2, model: TGateModel): TEdge
  return InstantiateNode(name, Color3.new(0.1, 0.4, 0.8), Enum.Material.SmoothPlastic, offset, model)
end

-- ----------------------------- ----- GATE MODEL INSTANTIATION ----- -----------------------------

local Models = { }

-- Casts Model -> TGateModel. Errors if types are not compatible
function Models.ToGateModel(model: any): TGateModel
  assert(model ~= nil and typeof(model) == "Instance" and model:IsA("Model"), "model was not of type Model")
  
  local nodes = model:FindFirstChild("Nodes")
  assert(nodes and nodes:IsA("Folder"), "'Nodes' was not found of valid type (Folder)")
  
  local base = model:FindFirstChild("Base")
  assert(base and (base:IsA("BasePart") or base:IsA("Model")), "'Base' was not found of valid type (BasePart | Model)")
  
  local decoration = model:FindFirstChild("Decoration")
  assert(decoration and decoration:IsA("Folder"), "'Decoration' was not found of valid type (Folder)")
  
  local main = decoration:FindFirstChild("Main")
  assert(main and (main:IsA("BasePart") or main:IsA("Model")), "'Main' was not found of valid type (BasePart | Model)")
  
  return model :: TGateModel
end

function Models.new(Nodes: { Outputs: { string }, Inputs: { string } }, visuals: Visuals.TVisuals): TGateModel
  -- Instantiate the gate prefab
  local prefab = PrefabsFolder.Gates:FindFirstChild(visuals.PrefabName)
  assert(prefab and prefab:IsA("Model"), "No gate prefab named '" .. visuals.PrefabName .. "'")
  
  local gateModel = Models.ToGateModel(prefab:Clone())
  do -- Decorate the Main part (Color, Material, DisplayName)
    local main = gateModel.Decoration.Main
  
    do
      local part = GetAsPart(main)
      part.Color = visuals.MainColor
      part.Material = visuals.MainMaterial
    end
    
    local nameDisplay = main:FindFirstChild("DisplayNameGui", true)
    if nameDisplay then
      local textLabel = nameDisplay:FindFirstChildWhichIsA("TextLabel")
      if textLabel then textLabel.Text = visuals.DisplayName end
    end
  end
  
  -- Classic boolean set. Used for Main deformation
  local edgesWithNode: TEdgeBoolset = { front = false, back = false, left = false, right = false }
  
  -- Instantiate Output nodes
  for i, outputName in ipairs(Nodes.Outputs) do
    local offset = visuals.OutputOffsets[i]
    local inEdge = InstantiateOutputNode(outputName, offset, gateModel)
    edgesWithNode[inEdge] = true
  end
  
  -- Instantiate Input nodes
  for i, inputName in ipairs(Nodes.Inputs) do
    local offset = visuals.InputOffsets[i]
    local inEdge = InstantiateInputNode(inputName, offset, gateModel)
    edgesWithNode[inEdge] = true
  end
  
  -- Scale decoration for nodes
  -- Only parts with the 'ScaleWithNodes' attribute (Boolean) will be scaled
  for _, child in ipairs(gateModel.Decoration:GetDescendants()) do
    if child:IsA("BasePart") and child:GetAttribute("ScaleWithNodes") then
      local newSize, baseRelativeOffset = MakeRoomForNodes(child, edgesWithNode)
      child.Size = newSize
      child.CFrame += GetAsPart(gateModel.Base).CFrame:VectorToWorldSpace(baseRelativeOffset)
    end
  end
  
  return gateModel
end

-- ----------------------------- ------------- END OF MODULE ------------- ---------------------------

return Models
