--!strict
--[[ GATE MODEL
    This defines the structure of a GateModel.
    It's the visual representation of a Gate object (Model Instance).
    
    A TGateModel should be a Model with the following children
      - Decorations: Folder
        - Main: BasePart ( Will be changed on the great Visuals update )
        - Others
      - Nodes: Folder
        - List of NodePrefabs
    	- Base: BasePart (2x0.3x2)
]]

-- Requires and Services
local ReplicatedStorage   = game:GetService("ReplicatedStorage")
local ServerScriptService = game:GetService("ServerScriptService")

local GateVisualsService = require(ReplicatedStorage.Services.GateVisualsService)

local Gate = require(ServerScriptService.Gates.Definitions.Gate)
local Node = require(ServerScriptService.Gates.Definitions.Node)

-- Prefabs
local PrefabsFolder = ReplicatedStorage.Gates.Prefabs
local NodePrefab: Part = PrefabsFolder.Node

-- Constants
local BASE_SIZE = Vector3.new(2, 0.3, 2)
-- This represents the transformation of moving up and back to prevent clipping down and sticking out
local NODE_DEPTH_OFFSET = CFrame.new(0, (NodePrefab.Size.Y + BASE_SIZE.Y) / 2, NodePrefab.Size.Z / 2)

-- ----------------------------- ---------- TYPE DEFINITIONS ----------- -----------------------------

type TEdge = "front" | "back" | "left" | "right"
type TEdgeBoolset = { front: boolean, back: boolean, left: boolean, right: boolean }

export type TGateModel = Model & {
  Decoration: Folder & { Main: BasePart },
  Nodes: Folder,
  Base: BasePart,
}

-- ----------------------------- ---------- HELPER FUNCTIONS ---------- ---------------------------

-- This function expects a Prepared Offset from GateVisualService.
-- Long story short: X < [-0.5, 0.5], Y < if Input [-0.15, 0.5] else [-0.5, -0.35].
--                  |X| == 0.5 Or |Y| == 0.5 always.
-- To prevent floating-point errors, I check against 1 / 10^9
-- It can be proven that the biggest error is 2^-53 (or ~ 1 / 10^16)
--   but I don't need that much precision. 1e-9 is the industry default
local function EdgeFromOffset(preparedOffset: Vector2): TEdge
  local function AlmostEqual(a: number, b: number): boolean return math.abs(a - b) < 1e-9 end  
  if     AlmostEqual(preparedOffset.Y,-0.5) then return "front"
  elseif AlmostEqual(preparedOffset.Y, 0.5) then return "back"
  elseif AlmostEqual(preparedOffset.X,-0.5) then return "left"
  elseif AlmostEqual(preparedOffset.X, 0.5) then return "right" end
  error("Prepared Offset was not prepared. Make sure it is a Vector2 generated by GateVisualService, or validate if sent from client.")
end

-- WireAttachment is on the back face. Should always point OUT of the gate
local RotationForEdge: { [TEdge]: CFrame } = {
  front = CFrame.Angles(0, math.rad(180), 0),
  back  = CFrame.Angles(0, 0, 0),
  left  = CFrame.Angles(0, math.rad(90), 0),
  right = CFrame.Angles(0, math.rad(-90), 0)
}

-- Magic!
-- Scales a part to make room for nodes.
-- The part is assumed to be centered
-- Returns (NewSize: Vector3, OffsetRelativeToBase: Vector3). Use part.CFrame + base.CFrame:VectorToWorldSpace(OffsetRelativeToBase) to transform
local function MakeRoomForNodes(--[[Out]] part: BasePart, edgesWithNode: TEdgeBoolset): (Vector3, Vector3)
  -- Calculate current distances from part's edges to Base's edges
  local leftDist  = (BASE_SIZE.x - part.Size.x) / 2
  local rightDist = leftDist
  local frontDist = (BASE_SIZE.z - part.Size.z) / 2
  local backDist  = frontDist
  
  -- Calculate needed shrink per side (only if current distance < NODE_DEPTH)
  local shrinkLeft  = if edgesWithNode.left  then math.max(NodePrefab.Size.z - leftDist,  0) else 0
  local shrinkRight = if edgesWithNode.right then math.max(NodePrefab.Size.z - rightDist, 0) else 0
  local shrinkFront = if edgesWithNode.front then math.max(NodePrefab.Size.z - frontDist, 0) else 0
  local shrinkBack  = if edgesWithNode.back  then math.max(NodePrefab.Size.z - backDist,  0) else 0
  
  -- New size is equal to the old size minus total shrink on each axis (Capped to 1.4, cause 2 - 0.3 * 2 == 1.4)
  -- If the original part is smaller than 1.4, then the size remains equal cause there is no need to make room for the nodes
  local newSizeX = math.max(part.Size.x - (shrinkLeft + shrinkRight), math.min(part.Size.x, 1.4))
  local newSizeZ = math.max(part.Size.z - (shrinkFront + shrinkBack), math.min(part.Size.z, 1.4))
  
  -- Calculate position offset to keep center aligned
  -- Move center away from edges that are shrinking to compensate
  local offsetX = (shrinkRight - shrinkLeft) / 2
  local offsetZ = (shrinkBack - shrinkFront) / 2
  
  return Vector3.new(newSizeX, part.Size.Y, newSizeZ), Vector3.new(offsetX, 0, offsetZ)
end

-- ----------------------------- --------- NODE INSTANTIATION --------- ---------------------------

-- Instantiates a node on the '[[out]] parent' gate.
-- Returns the edge where the node was created
local function CreateNode(name: string, nameColor: Color3, material: Enum.Material, offset: Vector2, --[[out]] parent: TGateModel): TEdge
  local node: Part = NodePrefab:Clone()
  node.Name = name
  node.Parent = parent.Nodes
  node.Material = material
  
  do -- Set fancy name in billboardGui
    local billboardGui = node:FindFirstChildWhichIsA("BillboardGui")
    if billboardGui then
      local textLabel = billboardGui:FindFirstChildWhichIsA("TextLabel")
      if textLabel then
        textLabel.Text = name
        textLabel.TextColor3 = nameColor
      end
    end
  end
  
  local edge: TEdge = EdgeFromOffset(offset)
  
  -- Linear transformation: SizeOffset × Rotation × Offset
  local nodeCframe: CFrame =
    NODE_DEPTH_OFFSET *
    RotationForEdge[edge] *
    CFrame.new(Vector3.new(offset.X * BASE_SIZE.X, 0, offset.Y * BASE_SIZE.Z))
  
  node.CFrame = parent.Base.CFrame:ToWorldSpace(nodeCframe)
  return edge
end

-- Output nodes will always have name "Output". Im hardcoding this in cause I have no intention of adding multiple outputs.
local function CreateOutput(offset: Vector2, --[[out]] parent: TGateModel): TEdge
  return CreateNode("Output", Color3.new(0.8, 0.1, 0.15), Enum.Material.Neon, offset, parent)
end

-- Of course, no designer/programmer would name an input node "Output", right?
local function CreateInput(name: string, offset: Vector2, --[[out]] parent: TGateModel): TEdge
  assert(name ~= "Output")
  return CreateNode(name, Color3.new(0.1, 0.4, 0.8), Enum.Material.SmoothPlastic, offset, parent)
end

-- ----------------------------- ----- GATE MODEL INSTANTIATION ----- -----------------------------

local GateModel = {}

-- Casts Model -> TGateModel. Errors if types are not compatible
function GateModel.ToGateModel(model: any): TGateModel
  assert(model ~= nil and typeof(model) == "Instance" and model:IsA("Model"), "model was not of type Model")
  
  local nodes = model:FindFirstChild("Nodes")
  assert(nodes and nodes:IsA("Folder"), "'Nodes' was not found of valid type (Folder)")
  
  local base = model:FindFirstChild("Base")
  assert(base and base:IsA("BasePart"), "'Base' was not found of valid type (BasePart)")
  
  local decoration = model:FindFirstChild("Decoration")
  assert(decoration and decoration:IsA("Folder"), "'Decoration' was not found of valid type (Folder)")
  
  local main = decoration:FindFirstChild("Main")
  assert(main and main:IsA("BasePart"), "'Main' was not found of valid type (BasePart)")

  if model.PrimaryPart == nil then
    model.PrimaryPart = base
  end
  
  return model :: TGateModel
end

-- CreateModel. Instantiates a new TGateModel. It does not follow GridService conditions automatically - that allows server to spawn as they like.
--   - Name is just for debugging
--   - It does NOT validate visuals either. Make sure PrefabName is a real prefab
function GateModel.CreateModel(name: string, nodeInformation: Node.TNodeInformation, visuals: GateVisualsService.TGateVisuals, cframe: CFrame): TGateModel
  visuals = GateVisualsService.Resolve(visuals, nodeInformation)

  -- Instantiate the gate prefab
  local prefab = PrefabsFolder.Gates:FindFirstChild(visuals.PrefabName)
  assert(prefab and prefab:IsA("Model"), "No gate prefab named '" .. visuals.PrefabName .. "'")
  
  local model: Model = prefab:Clone()
  model:PivotTo(cframe)
  model.Name = name
  
  local gateModel: TGateModel = GateModel.ToGateModel(model)
  
  do -- Decorate the Main part (Color, Material, DisplayName)
    local main = gateModel.Decoration.Main
    
    main.Color = visuals.MainColor
  	main.Material = visuals.MainMaterial
    
  	local nameDisplay = main:FindFirstChild("DisplayNameGui", true)
    if nameDisplay then
      local textLabel = nameDisplay:FindFirstChildWhichIsA("TextLabel")
      if textLabel then textLabel.Text = visuals.DisplayName end
    end
  end
  
  -- Classic boolean set. Used in Main deformation
  local edgesWithNode: TEdgeBoolset = { front = false, back = false, left = false, right = false }
  
  -- Instantiate the Output node
  if nodeInformation.HasOutput then
    local outEdge: TEdge = CreateOutput(visuals.OutputOffset, gateModel)
    edgesWithNode[outEdge] = true
  end
  
  -- Instantiate the Input nodes
  for _, inputName in ipairs(nodeInformation.Inputs) do
    local offset = visuals.InputOffsetOverrides[inputName] or error("Resolved visuals had no input offset for node '" .. inputName .. "'")
    local inEdge: TEdge = CreateInput(inputName, offset, gateModel)
    edgesWithNode[inEdge] = true
  end
  
  -- Scale decoration for nodes
  -- Only parts with the 'ScaleWithNodes' attribute (Boolean) will be scaled
  for _, child in ipairs(gateModel.Decoration:GetChildren()) do
    if child:IsA("BasePart") and child:GetAttribute("ScaleWithNodes") then
      local newSize, baseRelativeOffset = MakeRoomForNodes(child, edgesWithNode)
      child.Size = newSize
      child.CFrame += gateModel.Base.CFrame:VectorToWorldSpace(baseRelativeOffset)
    end
  end

  gateModel:SetAttribute("DisplayName", visuals.DisplayName)
  gateModel:SetAttribute("PrefabName", visuals.PrefabName)
  
  return gateModel
end

function GateModel.Instantiate(class: Gate.TGateClass, visuals: GateVisualsService.TGateVisuals, cframe: CFrame): TGateModel
  return GateModel.CreateModel(class.name, Gate.GetNodeInformation(class), visuals, cframe)
end

GateModel.instantiate = GateModel.Instantiate

-- ----------------------------- ------------- END OF MODULE ------------- ---------------------------

return GateModel
